/**
 * Automatic runtime behaviors — things the agent does without being asked.
 * Replaces tool-based observe/track_outcome/propose_task with automatic triggers.
 */

import { writeFile, readFile, mkdir } from "node:fs/promises";
import { CONTENT_HUB_DIR } from "./config.js";

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// --- Auto-observe after task completion ---

const OBS_FILE = `${CONTENT_HUB_DIR}/data/observations.md`;

export async function autoObserve(
  type: "rule" | "preference" | "fact" | "context" | "goal" | "habit" | "event",
  observation: string,
): Promise<void> {
  const date = today();
  const line = `[${type}] ${observation}`;

  let content: string;
  try {
    content = await readFile(OBS_FILE, "utf-8");
  } catch {
    content = `# Observations\n\n> Auto-generated by runtime. Consolidated by the dream cycle.\n> Types: [rule] [preference] [fact] [context] [goal] [habit] [event]\n\n`;
  }

  const dateHeader = `## ${date}`;
  if (content.includes(dateHeader)) {
    content = content.replace(dateHeader, `${dateHeader}\n${line}`);
  } else {
    content += `\n${dateHeader}\n${line}\n`;
  }

  await writeFile(OBS_FILE, content, "utf-8");
}

// --- Auto-track outcome after publishing ---

const OUTCOMES_DIR = `${CONTENT_HUB_DIR}/data/outcomes`;

export async function autoTrackOutcome(
  contentType: "tweet" | "video" | "skool_post" | "bluesky_post" | "article" | "blog_post",
  contentId: string,
  description: string,
  checkAfterHours = 24,
): Promise<void> {
  await mkdir(OUTCOMES_DIR, { recursive: true });

  const outcome = {
    content_type: contentType,
    content_id: contentId,
    description,
    posted_at: new Date().toISOString(),
    check_at: new Date(Date.now() + checkAfterHours * 3600_000).toISOString(),
    checked: false,
  };

  const file = `${OUTCOMES_DIR}/${today()}.json`;
  let outcomes: unknown[] = [];
  try {
    outcomes = JSON.parse(await readFile(file, "utf-8"));
  } catch { /* empty */ }
  outcomes.push(outcome);
  await writeFile(file, JSON.stringify(outcomes, null, 2));
}

// --- Auto-observe task results ---

export async function observeTaskResult(
  taskName: string,
  success: boolean,
  cost: number,
  turns: number,
  summary: string,
): Promise<void> {
  // Only observe noteworthy results
  if (!success) {
    await autoObserve("event", `Task ${taskName} failed ($${cost.toFixed(2)}, ${turns}t): ${summary.slice(0, 200)}`);
  } else if (cost > 5) {
    await autoObserve("event", `Task ${taskName} was expensive ($${cost.toFixed(2)}, ${turns}t)`);
  }

  // Detect publishing and auto-track outcomes
  const publishKeywords = ["posted", "published", "uploaded", "tweeted"];
  const isPublish = publishKeywords.some(k => summary.toLowerCase().includes(k));

  if (success && isPublish) {
    // Try to extract URL from response
    const urlMatch = summary.match(/https?:\/\/[^\s)]+/);
    const contentType = detectContentType(taskName, summary);
    if (contentType) {
      await autoTrackOutcome(
        contentType,
        urlMatch?.[0] ?? taskName,
        summary.slice(0, 200),
      );
    }
  }
}

function detectContentType(
  taskName: string,
  text: string,
): "tweet" | "video" | "skool_post" | "bluesky_post" | "article" | "blog_post" | null {
  if (taskName.includes("viral") || taskName.includes("social") || taskName.includes("cta")) return "tweet";
  if (taskName.includes("skool")) return "skool_post";
  if (taskName.includes("article")) return "article";
  if (text.toLowerCase().includes("bluesky")) return "bluesky_post";
  if (text.toLowerCase().includes("youtube") || text.toLowerCase().includes("video")) return "video";
  if (text.toLowerCase().includes("blog") || text.toLowerCase().includes("notipo")) return "blog_post";
  return null;
}
