/**
 * Automatic runtime behaviors — things the agent does without being asked.
 * Replaces tool-based observe/track_outcome/propose_task with automatic triggers.
 */

import { writeFile, readFile, mkdir } from "node:fs/promises";
import { KODA_HOME } from "./config.js";

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// --- Auto-observe after task completion ---

const OBS_FILE = `${KODA_HOME}/data/observations.md`;

export async function autoObserve(
  type: "rule" | "preference" | "fact" | "context" | "goal" | "habit" | "event",
  observation: string,
): Promise<void> {
  const date = today();
  const line = `[${type}] ${observation}`;

  let content: string;
  try {
    content = await readFile(OBS_FILE, "utf-8");
  } catch {
    content = `# Observations\n\n> Auto-generated by runtime. Consolidated by the dream cycle.\n> Types: [rule] [preference] [fact] [context] [goal] [habit] [event]\n\n`;
  }

  const dateHeader = `## ${date}`;
  if (content.includes(dateHeader)) {
    content = content.replace(dateHeader, `${dateHeader}\n${line}`);
  } else {
    content += `\n${dateHeader}\n${line}\n`;
  }

  // Cap at 500 lines — drop oldest entries to prevent bloat between dream cycles
  const lines = content.split("\n");
  if (lines.length > 500) {
    // Keep header (first 5 lines) + newest entries
    const header = lines.slice(0, 5);
    const body = lines.slice(5);
    content = [...header, ...body.slice(body.length - 495)].join("\n");
  }

  await writeFile(OBS_FILE, content, "utf-8");
}

// --- Auto-track outcome after publishing ---

const OUTCOMES_DIR = `${KODA_HOME}/data/outcomes`;

export async function autoTrackOutcome(
  contentType: "tweet" | "video" | "skool_post" | "bluesky_post" | "article" | "blog_post",
  contentId: string,
  description: string,
  checkAfterHours = 24,
): Promise<void> {
  await mkdir(OUTCOMES_DIR, { recursive: true });

  const outcome = {
    content_type: contentType,
    content_id: contentId,
    description,
    posted_at: new Date().toISOString(),
    check_at: new Date(Date.now() + checkAfterHours * 3600_000).toISOString(),
    checked: false,
  };

  const file = `${OUTCOMES_DIR}/${today()}.json`;
  let outcomes: unknown[] = [];
  try {
    outcomes = JSON.parse(await readFile(file, "utf-8"));
  } catch { /* empty */ }
  outcomes.push(outcome);
  await writeFile(file, JSON.stringify(outcomes, null, 2));
}

// --- Auto-observe task results ---

export async function observeTaskResult(
  taskName: string,
  success: boolean,
  cost: number,
  turns: number,
  summary: string,
): Promise<void> {
  // Only observe noteworthy results
  if (!success) {
    await autoObserve("event", `Task ${taskName} failed ($${cost.toFixed(2)}, ${turns}t): ${summary.slice(0, 200)}`);
  } else if (cost > 5) {
    await autoObserve("event", `Task ${taskName} was expensive ($${cost.toFixed(2)}, ${turns}t)`);
  }

  // Detect publishing and auto-track outcomes
  const publishKeywords = ["posted", "published", "uploaded", "tweeted"];
  const isPublish = publishKeywords.some(k => summary.toLowerCase().includes(k));

  if (success && isPublish) {
    // Try to extract URL from response
    const urlMatch = summary.match(/https?:\/\/[^\s)]+/);
    const contentType = detectContentType(taskName, summary);
    if (contentType) {
      await autoTrackOutcome(
        contentType,
        urlMatch?.[0] ?? taskName,
        summary.slice(0, 200),
      );
    }
  }
}

// --- Freshness warnings for stale memories ---

/**
 * Check learnings.md for stale entries and return warning text.
 * Called at startup and after dream cycles to flag outdated knowledge.
 */
export async function checkMemoryFreshness(): Promise<string | null> {
  const learningsFile = `${KODA_HOME}/learnings.md`;
  const obsFile = OBS_FILE;
  const warnings: string[] = [];

  // Check learnings.md modification time
  try {
    const { stat } = await import("node:fs/promises");
    const s = await stat(learningsFile);
    const ageDays = Math.floor((Date.now() - s.mtimeMs) / 86_400_000);
    if (ageDays > 14) {
      warnings.push(`learnings.md hasn't been updated in ${ageDays} days — content may be stale. Verify before acting on it.`);
    }
  } catch { /* file doesn't exist */ }

  // Check observations.md for old undated entries
  try {
    const content = await readFile(obsFile, "utf-8");
    const datePattern = /^## (\d{4}-\d{2}-\d{2})/gm;
    let oldestDate: string | null = null;
    let match: RegExpExecArray | null;
    while ((match = datePattern.exec(content)) !== null) {
      if (!oldestDate || match[1] < oldestDate) oldestDate = match[1];
    }
    if (oldestDate) {
      const ageDays = Math.floor((Date.now() - new Date(oldestDate).getTime()) / 86_400_000);
      if (ageDays > 30) {
        warnings.push(`observations.md has entries from ${oldestDate} (${ageDays} days ago). Dream cycle should prune these.`);
      }
    }
  } catch { /* file doesn't exist */ }

  return warnings.length > 0 ? warnings.join("\n") : null;
}

/**
 * Wrap a memory string with a freshness note if it's old.
 * Matches the leak's memoryFreshnessNote pattern.
 */
export function addFreshnessNote(content: string, mtimeMs: number): string {
  const ageDays = Math.floor((Date.now() - mtimeMs) / 86_400_000);
  if (ageDays <= 7) return content;

  const note = ageDays <= 30
    ? `Note: this memory is ${ageDays} days old. It should still be accurate but verify critical details against current state.`
    : `Warning: this memory is ${ageDays} days old and may be significantly outdated. Verify against current code/config before relying on it.`;

  return `[FRESHNESS: ${note}]\n\n${content}`;
}

function detectContentType(
  taskName: string,
  text: string,
): "tweet" | "video" | "skool_post" | "bluesky_post" | "article" | "blog_post" | null {
  if (taskName.includes("viral") || taskName.includes("social") || taskName.includes("cta")) return "tweet";
  if (taskName.includes("skool")) return "skool_post";
  if (taskName.includes("article")) return "article";
  if (text.toLowerCase().includes("bluesky")) return "bluesky_post";
  if (text.toLowerCase().includes("youtube") || text.toLowerCase().includes("video")) return "video";
  if (text.toLowerCase().includes("blog")) return "blog_post";
  return null;
}
