import { tool, createSdkMcpServer } from "@anthropic-ai/claude-agent-sdk";
import { z } from "zod";
import { writeFile, readFile, mkdir, stat } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { KODA_HOME } from "../config.js";

const execFileAsync = promisify(execFile);

function textResult(text: string) {
  return { content: [{ type: "text" as const, text }] };
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// --- Observation system ---

const OBS_FILE = `${KODA_HOME}/data/observations.md`;

const observe = tool(
  "observe",
  "Record an observation for memory consolidation. NOTE: observations are now recorded " +
  "automatically after tasks — only use this for ad-hoc observations during conversations. " +
  "Types: rule (permanent), preference (how user likes things), fact (learned info), " +
  "context (temporary situation), goal (objective), habit (recurring pattern), event (one-time).",
  {
    type: z.enum(["rule", "preference", "fact", "context", "goal", "habit", "event"]),
    observation: z.string().max(500),
  },
  async ({ type, observation }) => {
    const date = today();
    const line = `[${type}] ${observation}`;

    let content: string;
    try {
      content = await readFile(OBS_FILE, "utf-8");
    } catch {
      content = `# Observations\n\n> Auto-generated by the observer. Consolidated by the dream cycle.\n> Each entry has a date, type tag, and the observation.\n> Types: [rule] [preference] [fact] [context] [goal] [habit] [event]\n\n`;
    }

    // Check if today's section exists
    const dateHeader = `## ${date}`;
    if (content.includes(dateHeader)) {
      content = content.replace(dateHeader, `${dateHeader}\n${line}`);
    } else {
      // Add new date section after the header
      const headerEnd = content.indexOf("\n\n", content.indexOf("> Types:"));
      if (headerEnd > 0) {
        content =
          content.slice(0, headerEnd + 2) +
          `\n${dateHeader}\n${line}\n` +
          content.slice(headerEnd + 2);
      } else {
        content += `\n${dateHeader}\n${line}\n`;
      }
    }

    await writeFile(OBS_FILE, content, "utf-8");
    return textResult(`Observed: [${type}] ${observation}`);
  },
);

// --- Self-initiated task queue ---

const INITIATIVE_FILE = `${KODA_HOME}/data/.agent-initiatives.json`;

interface Initiative {
  id: string;
  description: string;
  reason: string;
  priority: "low" | "medium" | "high";
  created: string;
  status: "pending" | "approved" | "rejected" | "done";
}

async function loadInitiatives(): Promise<Initiative[]> {
  try {
    const data = await readFile(INITIATIVE_FILE, "utf-8");
    return JSON.parse(data);
  } catch {
    return [];
  }
}

async function saveInitiatives(items: Initiative[]): Promise<void> {
  await mkdir(`${KODA_HOME}/data`, { recursive: true });
  await writeFile(INITIATIVE_FILE, JSON.stringify(items, null, 2));
}

const proposeTask = tool(
  "propose_task",
  "Propose a self-initiated task. Use when you identify something that should be done " +
  "based on your analysis — e.g., a goal is behind, content is performing poorly, " +
  "or an opportunity was spotted. HIGH priority tasks are sent to Discord for approval. " +
  "LOW priority tasks you can execute autonomously.",
  {
    description: z.string(),
    reason: z.string().describe("Why this task should be done — what triggered it"),
    priority: z.enum(["low", "medium", "high"]),
  },
  async ({ description, reason, priority }) => {
    const initiatives = await loadInitiatives();
    const id = `init-${Date.now()}`;
    const initiative: Initiative = {
      id,
      description,
      reason,
      priority,
      created: new Date().toISOString(),
      status: priority === "low" ? "approved" : "pending",
    };
    initiatives.push(initiative);
    await saveInitiatives(initiatives);

    if (priority === "low") {
      return textResult(
        `Task auto-approved (low priority): ${description}\nYou may execute it now.`,
      );
    }
    return textResult(
      `Task proposed (${priority} priority): ${description}\n` +
      `Reason: ${reason}\n` +
      `Awaiting user approval via Discord. ID: ${id}`,
    );
  },
);

// --- Outcome tracking ---

const OUTCOMES_DIR = `${KODA_HOME}/data/outcomes`;

const trackOutcome = tool(
  "track_outcome",
  "Schedule an outcome check for content that was just published. " +
  "After 24-48 hours, you should check how it performed and record an observation. " +
  "Use this after posting a tweet, publishing a video, or creating a Skool post.",
  {
    content_type: z.enum(["tweet", "video", "skool_post", "bluesky_post", "article"]),
    content_id: z.string().describe("URL, tweet ID, or identifier"),
    description: z.string().describe("Brief description of what was posted"),
    check_after_hours: z.number().default(24),
  },
  async ({ content_type, content_id, description, check_after_hours }) => {
    await mkdir(OUTCOMES_DIR, { recursive: true });

    const outcome = {
      content_type,
      content_id,
      description,
      posted_at: new Date().toISOString(),
      check_at: new Date(Date.now() + check_after_hours * 3600_000).toISOString(),
      checked: false,
    };

    const file = `${OUTCOMES_DIR}/${today()}.json`;
    let outcomes: unknown[] = [];
    try {
      outcomes = JSON.parse(await readFile(file, "utf-8"));
    } catch {
      // empty
    }
    outcomes.push(outcome);
    await writeFile(file, JSON.stringify(outcomes, null, 2));

    return textResult(
      `Tracking outcome for ${content_type}: ${description}\n` +
      `Will check performance in ${check_after_hours} hours.`,
    );
  },
);

// --- ULTRAPLAN ---

const PLANS_DIR = `${KODA_HOME}/data/plans`;

const ultraplan = tool(
  "ultraplan",
  "Create a detailed execution plan for a complex, multi-step task. " +
  "Use this when a task requires research, multiple phases, or coordination. " +
  "The plan is saved to disk and sent to Discord for user approval before execution. " +
  "Do NOT execute the plan — only create it. Wait for approval.",
  {
    title: z.string().describe("Short title for the plan"),
    goal: z.string().describe("What this plan aims to achieve"),
    phases: z.array(z.object({
      name: z.string(),
      description: z.string(),
      agent: z.enum(["researcher", "implementer", "verifier"]).optional(),
      estimated_turns: z.number().optional(),
    })).describe("Ordered phases of execution"),
    risks: z.array(z.string()).optional().describe("What could go wrong"),
    success_criteria: z.array(z.string()).describe("How to know the plan succeeded"),
  },
  async ({ title, goal, phases, risks, success_criteria }) => {
    await mkdir(PLANS_DIR, { recursive: true });

    const plan = {
      id: `plan-${Date.now()}`,
      title,
      goal,
      phases,
      risks: risks ?? [],
      success_criteria,
      created: new Date().toISOString(),
      status: "pending_approval",
    };

    const file = `${PLANS_DIR}/${plan.id}.json`;
    await writeFile(file, JSON.stringify(plan, null, 2));

    // Format for Discord
    const phasesText = phases
      .map((p, i) => `${i + 1}. **${p.name}**${p.agent ? ` (${p.agent})` : ""}: ${p.description}`)
      .join("\n");
    const risksText = (risks ?? []).length > 0
      ? `\n**Risks:**\n${risks!.map(r => `- ${r}`).join("\n")}`
      : "";
    const criteriaText = success_criteria.map(c => `- ${c}`).join("\n");

    return textResult(
      `**ULTRAPLAN: ${title}**\n` +
      `**Goal:** ${goal}\n\n` +
      `**Phases:**\n${phasesText}\n` +
      `${risksText}\n` +
      `**Success criteria:**\n${criteriaText}\n\n` +
      `Plan saved as ${plan.id}. Send this to Discord for approval. ` +
      `When approved, execute phases in order using the appropriate subagents.`,
    );
  },
);

// --- Self-healing tools ---

const LOG_OUT = `${KODA_HOME}/logs/koda-out.log`;
const LOG_ERR = `${KODA_HOME}/logs/koda-error.log`;

const checkHealth = tool(
  "check_health",
  "Check Koda's own health: pm2 status, recent errors, log file sizes, and config validity.",
  {},
  async () => {
    const results: string[] = [];

    // pm2 status
    try {
      const { stdout } = await execFileAsync("pm2", ["jlist"]);
      const procs: Array<{ name: string; pm2_env?: { status: string; restart_time: number; pm_uptime?: number } }> = JSON.parse(stdout);
      const koda = procs.find(p => p.name === "koda");
      if (koda) {
        const status = koda.pm2_env?.status ?? "unknown";
        const restarts = koda.pm2_env?.restart_time ?? 0;
        const uptimeSec = koda.pm2_env?.pm_uptime
          ? Math.floor((Date.now() - koda.pm2_env.pm_uptime) / 1000)
          : null;
        results.push(`pm2: ${status}, restarts=${restarts}${uptimeSec !== null ? `, uptime=${uptimeSec}s` : ""}`);
      } else {
        results.push("pm2: koda process not found");
      }
    } catch (err) {
      results.push(`pm2: error — ${err instanceof Error ? err.message : String(err)}`);
    }

    // Log file sizes + last error
    for (const [label, path] of [["stdout", LOG_OUT], ["stderr", LOG_ERR]]) {
      try {
        const s = await stat(path);
        const kb = Math.round(s.size / 1024);
        results.push(`${label}: ${kb}KB (${path})`);
      } catch {
        results.push(`${label}: not found`);
      }
    }

    // Last 20 lines of error log
    try {
      const { stdout } = await execFileAsync("tail", ["-n", "20", LOG_ERR]);
      if (stdout.trim()) {
        results.push(`\nRecent errors:\n${stdout.trim()}`);
      } else {
        results.push("Recent errors: none");
      }
    } catch {
      results.push("Recent errors: could not read");
    }

    return textResult(results.join("\n"));
  },
);

const restartSelf = tool(
  "restart_self",
  "Restart the Koda pm2 process. Use after config changes or to recover from errors. " +
  "WARNING: this will interrupt the current session. Only use if necessary.",
  {
    reason: z.string().describe("Why the restart is needed"),
  },
  async ({ reason }) => {
    console.log(`[agent-tools] restart_self called: ${reason}`);
    // Delay slightly so the tool result can be returned before the process dies
    setTimeout(async () => {
      try {
        await execFileAsync("pm2", ["restart", "koda"]);
      } catch (err) {
        console.error("[agent-tools] restart_self failed:", err);
      }
    }, 2000);
    return textResult(`Restarting in 2s. Reason: ${reason}`);
  },
);

// --- MCP Server ---

export const agentToolsServer = createSdkMcpServer({
  name: "agent-tools",
  version: "0.1.0",
  tools: [observe, proposeTask, trackOutcome, ultraplan, checkHealth, restartSelf],
});
