import { tool, createSdkMcpServer } from "@anthropic-ai/claude-agent-sdk";
import { z } from "zod";
import { writeFile, readFile, mkdir } from "node:fs/promises";
import { CONTENT_HUB_DIR } from "../config.js";

function textResult(text: string) {
  return { content: [{ type: "text" as const, text }] };
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// --- Observation system ---

const OBS_FILE = `${CONTENT_HUB_DIR}/data/observations.md`;

const observe = tool(
  "observe",
  "Record an observation for memory consolidation. Use this whenever you notice " +
  "something worth remembering: a pattern, a preference, a fact, a result. " +
  "The dream cycle will consolidate these into LEARNINGS.md over time. " +
  "Types: rule (permanent), preference (how user likes things), fact (learned info), " +
  "context (temporary situation), goal (objective), habit (recurring pattern), event (one-time).",
  {
    type: z.enum(["rule", "preference", "fact", "context", "goal", "habit", "event"]),
    observation: z.string().max(500),
  },
  async ({ type, observation }) => {
    const date = today();
    const line = `[${type}] ${observation}`;

    let content: string;
    try {
      content = await readFile(OBS_FILE, "utf-8");
    } catch {
      content = `# Observations\n\n> Auto-generated by the observer. Consolidated by the dream cycle.\n> Each entry has a date, type tag, and the observation.\n> Types: [rule] [preference] [fact] [context] [goal] [habit] [event]\n\n`;
    }

    // Check if today's section exists
    const dateHeader = `## ${date}`;
    if (content.includes(dateHeader)) {
      content = content.replace(dateHeader, `${dateHeader}\n${line}`);
    } else {
      // Add new date section after the header
      const headerEnd = content.indexOf("\n\n", content.indexOf("> Types:"));
      if (headerEnd > 0) {
        content =
          content.slice(0, headerEnd + 2) +
          `\n${dateHeader}\n${line}\n` +
          content.slice(headerEnd + 2);
      } else {
        content += `\n${dateHeader}\n${line}\n`;
      }
    }

    await writeFile(OBS_FILE, content, "utf-8");
    return textResult(`Observed: [${type}] ${observation}`);
  },
);

// --- Self-initiated task queue ---

const INITIATIVE_FILE = `${CONTENT_HUB_DIR}/data/.agent-initiatives.json`;

interface Initiative {
  id: string;
  description: string;
  reason: string;
  priority: "low" | "medium" | "high";
  created: string;
  status: "pending" | "approved" | "rejected" | "done";
}

async function loadInitiatives(): Promise<Initiative[]> {
  try {
    const data = await readFile(INITIATIVE_FILE, "utf-8");
    return JSON.parse(data);
  } catch {
    return [];
  }
}

async function saveInitiatives(items: Initiative[]): Promise<void> {
  await mkdir(`${CONTENT_HUB_DIR}/data`, { recursive: true });
  await writeFile(INITIATIVE_FILE, JSON.stringify(items, null, 2));
}

const proposeTask = tool(
  "propose_task",
  "Propose a self-initiated task. Use when you identify something that should be done " +
  "based on your analysis — e.g., a goal is behind, content is performing poorly, " +
  "or an opportunity was spotted. HIGH priority tasks are sent to Discord for approval. " +
  "LOW priority tasks you can execute autonomously.",
  {
    description: z.string(),
    reason: z.string().describe("Why this task should be done — what triggered it"),
    priority: z.enum(["low", "medium", "high"]),
  },
  async ({ description, reason, priority }) => {
    const initiatives = await loadInitiatives();
    const id = `init-${Date.now()}`;
    const initiative: Initiative = {
      id,
      description,
      reason,
      priority,
      created: new Date().toISOString(),
      status: priority === "low" ? "approved" : "pending",
    };
    initiatives.push(initiative);
    await saveInitiatives(initiatives);

    if (priority === "low") {
      return textResult(
        `Task auto-approved (low priority): ${description}\nYou may execute it now.`,
      );
    }
    return textResult(
      `Task proposed (${priority} priority): ${description}\n` +
      `Reason: ${reason}\n` +
      `Awaiting user approval via Discord. ID: ${id}`,
    );
  },
);

// --- Outcome tracking ---

const OUTCOMES_DIR = `${CONTENT_HUB_DIR}/data/outcomes`;

const trackOutcome = tool(
  "track_outcome",
  "Schedule an outcome check for content that was just published. " +
  "After 24-48 hours, you should check how it performed and record an observation. " +
  "Use this after posting a tweet, publishing a video, or creating a Skool post.",
  {
    content_type: z.enum(["tweet", "video", "skool_post", "bluesky_post", "article"]),
    content_id: z.string().describe("URL, tweet ID, or identifier"),
    description: z.string().describe("Brief description of what was posted"),
    check_after_hours: z.number().default(24),
  },
  async ({ content_type, content_id, description, check_after_hours }) => {
    await mkdir(OUTCOMES_DIR, { recursive: true });

    const outcome = {
      content_type,
      content_id,
      description,
      posted_at: new Date().toISOString(),
      check_at: new Date(Date.now() + check_after_hours * 3600_000).toISOString(),
      checked: false,
    };

    const file = `${OUTCOMES_DIR}/${today()}.json`;
    let outcomes: unknown[] = [];
    try {
      outcomes = JSON.parse(await readFile(file, "utf-8"));
    } catch {
      // empty
    }
    outcomes.push(outcome);
    await writeFile(file, JSON.stringify(outcomes, null, 2));

    return textResult(
      `Tracking outcome for ${content_type}: ${description}\n` +
      `Will check performance in ${check_after_hours} hours.`,
    );
  },
);

// --- MCP Server ---

export const agentToolsServer = createSdkMcpServer({
  name: "agent-tools",
  version: "0.1.0",
  tools: [observe, proposeTask, trackOutcome],
});
